composer.json:
  - ./composer.json

.github:
  - .github/*
  - .github/**/*

.gitignore:
  - .gitignore

config (tooling):
  - ./*.dist
  - ./*.dist.*
  - .github/*.yml

tests (unit):
  - tests/*

tests (example):
  - examples/*

code-change:
  - src/*

release:
  - ./CHANGELOG.md

documentation:
  - ./*.md
  - ./**/*.md

php:
  - ./**/*.php

shell:
  - ./*.sh
  - ./**/*.sh
